version: '3'
services:
  user-db:
    image: "postgres:13"
    container_name: user-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: peerprep
    volumes:
      - user-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

  user-service:
    build:
      context: .
      dockerfile: ./dockerfiles/dockerfile.user-service
    ports:
      - "5000:5000" # map host port:5000 to container's port:5000
    environment:
      MONGOURL: mongodb+srv://peerprep15:CRFVdZNswqisruzv@peerprep.vmiy632.mongodb.net/?retryWrites=true&w=majority
      PG_USER: postgres
      PG_PASSWORD: 12345
      PG_DB: peerprep
      PG_HOST: user-db
    depends_on: 
      user-db:
        condition: service_healthy
    restart: on-failure