name: User service CI Pipeline
on:
  push:
    branches:
      - master

env:
  MONGOURL: ${{ secrets.MONGO_URL }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_DB: ${{ secrets.PG_DB }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_URL: ${{ secrets.PG_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies for user-service
        run: cd user-service && npm install
        
      - name: Run Tests for user-service
        run: npm run test:ci

      - name: Stop postgres service
        run: docker-compose down